### ISSUE TITLE
Lexical score calculation

### ISSUE THREAD

**Issue by achingacham** [IBM/quality-controlled-paraphrase-generation#10]
Hi there!

First of all, a big thanks to all contributors for this interesting work!

As I am trying to understand different quality dimensions in this work, I found that the lexical score is not a trivial choice. 
In the paper, it is mentioned as:

>We define the lexical score qlex(s, s′) to be the normalized character-level minimal edit distance between the bag of words. 

I am unable to comprehend the idea of edit distance over BoW and also couldn't find its implementation in the code base. 
Can someone please redirect me to the location in this repo where it is defined? 

regards,
Anupama

**Comment by achingacham** [comment]
Hi @elronbandel, Could you please give some leads here?

**Comment by elronbandel** [comment]
This is the code line:

https://github.com/IBM/quality-controlled-paraphrase-generation/blob/de3e8534142d2e72d463a0cc4df0339439f5bdfe/metrics/para_metric/para_metric.py#L86

This is the underlying function for computing the lexical similarity:

https://maxbachmann.github.io/Levenshtein/levenshtein.html#setratio

Defined there as:

"Compute similarity ratio of two strings sets (passed as sequences).

The best match between any strings in the first set and the second set (passed as sequences) is attempted. I.e., the order doesn’t matter here."

@achingacham

**Comment by achingacham** [comment]
Thanks a lot, @elronbandel for the prompt response! That's quite a help.
