### ISSUE TITLE
QP module 

### ISSUE THREAD

**Issue by alexcoca** [IBM/quality-controlled-paraphrase-generation#5]
I was wondering if it is possible to upload your quality predictor module to the `huggingface` hub and post brief instructions on how to run inference with it for a given sentence to be paraphrased (an example in the model card will suffice) to obtain the quality vectors.

This will help other researchers replicate your work without the need to retrain the model (avoiding reproducibility issues as well as helping researchers working with very scarce resources).

Thank you in advance.

**Comment by alexcoca** [comment]
@elronbandel is there any chance you will publish this? Or is this module automatically called in the pipeline and I am just inputting the offsets here?

**Comment by nehasrikn** [comment]
+1 Would love to use the quality predictor module for some of my experiments. @elronbandel Is there a chance you can shed light on this?

**Comment by elronbandel** [comment]
The reason we did not upload the Quality Predictor checkpoint yet with the rest of the code and checkpoints is that at the time we were still conducting some experiments with it.

We wanted to verify the empirical importance of the quality predictor for the creation of the semantic/linguistic heatmaps presented in the paper.  The heatmaps measure the success of the paraphrasing model in terms of semantic similarity and linguistic diversity as function of the **offset** from the quality predictor values. Another option is to create such success heatmaps as function of the control values directly. 
Our conclusion is that although the offsets from the quality predictor values are better for predicting the success of the paraphrasing models, and as such, creating better heatmaps, this advantage was marginal. That means that although being more theoretically correct, the value of the quality predictor in practice is minor. 
Notice that this result does not imply anything about the analysis, method and the results described in the paper which are correct and accurate (and in our opinion very useful for the community😇),  just that the practical contribution of the quality predictor int the pipeline is minor. The heatmaps are still crucial for choosing the right quality control values and quality controlled generation is still a better way to learn the distribution of the data allowing for high quality generation🤩

Anyways, thank you for showing interest in our work! We will upload the quality predictor checkpoints this week

If you have any more question or thoughts feel free to contact me at elronbandel@gmail.com 
Would love to hear from you! 
@alexcoca @nehasrikn

**Comment by nehasrikn** [comment]
Wonderful, thanks for the update @elronbandel! And thanks for your fabulous work — really loved the paper and thank you for making the models so accessible :)

**Comment by elronbandel** [comment]
QP is uploaded to 🤗 hub:
- [qp-sentences](https://huggingface.co/ibm/qp-sentences)
- [qp-captions](https://huggingface.co/ibm/qp-captions)
- [qp-questions](https://huggingface.co/ibm/qp-questions)

**Comment by nehasrikn** [comment]
@elronbandel really appreciate you keeping us updated! :) thank you for all your hard work in making this publicly available!

**Comment by alexcoca** [comment]
@elronbandel Yes, thanks so much. I did not end up using the QP module, but your model was actually quite useful! Thank you for quality code and making everything useable!
