### ISSUE TITLE
Length of generated sentence

### ISSUE THREAD

**Issue by OlegVasilyev4096** [IBM/quality-controlled-paraphrase-generation#6]
When input is a long sentence, the model, as I noticed (using your example code), still generates a very short paraphrase, which sometimes looks like cut off in the middle or even earlier. 
What is the best way to allow for the generated paraphrase to have the length at least comparable to the length of the input sentence?

**Comment by alexcoca** [comment]
I would try to pass the `min_length` and `max_length` parameters to the pipeline as documented here:

https://huggingface.co/docs/transformers/v4.21.3/en/main_classes/text_generation#transformers.generation_utils.GenerationMixin.generate

**Comment by OlegVasilyev4096** [comment]
Thanks, that solves it.
